### ISSUE TITLE
Uncaught TypeError: element.addEventListener is not a function

### ISSUE THREAD

**Issue by seminice** [sindresorhus/atom-jshint#143]
[Enter steps to reproduce below:]
1. just use jshint ..... this happened after I updated...... can I revert?
2. ...
   Btw updating my jshintrc doesnt change anything untill I restart atom.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.8.5
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.3
### Stack Trace

Uncaught TypeError: element.addEventListener is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/delegated-listener.js:36

TypeError: element.addEventListener is not a function
  at listen (/Applications/Atom.app/Contents/Resources/app.asar/src/delegated-listener.js:36:11)
  at [object Object].Tooltip.init (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip.js:83:28)
  at new Tooltip (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip.js:18:8)
  at TooltipManager.module.exports.TooltipManager.add (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip-manager.js:50:17)
  at addReasons (/Users/user/.atom/packages/jshint/index.js:186:30)
  at displayError (/Users/user/.atom/packages/jshint/index.js:206:2)
  at /Users/user/.atom/packages/jshint/index.js:214:10
  at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
  at displayErrors (/Users/user/.atom/packages/jshint/index.js:213:4)
  at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
  at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)

```
### Commands

```
     -0:11 core:copy (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:07.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.characterwise)
  3x -0:05.5.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
```
### Config

``` json
{
  "core": {},
  "jshint": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.3
autoclose-html, v0.19.0
jshint, v1.8.3
pigments, v0.18.1
seti-icons, v0.4.5
vim-mode-plus, v0.1.7
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by amhed** [comment]
Same here

**Comment by finian** [comment]
+1

**Comment by ArtskydJ** [comment]
Similar to #124.

**Comment by philidem** [comment]
:+1:

**Comment by zp-j** [comment]
Is there any temporary solution to hide this TypeError? Thanks!

**Comment by SylvainLefevre** [comment]
just install last jshint package to resolve problem : apm install jshint

**Comment by zp-j** [comment]
Thanks, but I still have this issue after updating :(

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.2
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.8.3


### Stack Trace

Uncaught TypeError: element.addEventListener is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/delegated-listener.js:36

TypeError: element.addEventListener is not a function
  at listen (/Applications/Atom.app/Contents/Resources/app.asar/src/delegated-listener.js:36:11)
  at [object Object].Tooltip.init (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip.js:83:28)
  at new Tooltip (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip.js:18:8)
  at TooltipManager.module.exports.TooltipManager.add (/Applications/Atom.app/Contents/Resources/app.asar/src/tooltip-manager.js:50:17)
  at addReasons (/Users/zhipeng/.atom/packages/jshint/index.js:186:30)
  at displayError (/Users/zhipeng/.atom/packages/jshint/index.js:206:2)
  at /Users/zhipeng/.atom/packages/jshint/index.js:214:10
  at arrayEach (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1289:13)
  at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:3345:13)
  at displayErrors (/Users/zhipeng/.atom/packages/jshint/index.js:213:4)
  at lint (/Users/zhipeng/.atom/packages/jshint/index.js:293:2)
  at complete (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
  at delayed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)

```

### Commands

```
     -0:40.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.7.0 core:move-left (atom-text-editor.editor.is-focused)
  9x -0:35.4.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:33.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:30.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
 14x -0:28.6.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:24.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:23.4.0 core:move-left (atom-text-editor.editor.is-focused)
 32x -0:23 core:move-right (atom-text-editor.editor.is-focused)
 14x -0:19.3.0 core:move-down (atom-text-editor.editor.is-focused)
  6x -0:15.9.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:14.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:13.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:10.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10.6.0 settings-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.16
docblockr, v0.7.3
highlight-selected, v0.10.1
jshint, v1.8.3
language-latex, v0.6.1
monokai, v0.18.0

# Dev
No dev packages
```

**Comment by TimMensch** [comment]
I see the same crash after getting 1.8.3, and don't see how to install an older jshint.

**Comment by ArtskydJ** [comment]
I'm having trouble replicating this issue, and I'm on v1.8.3.

Are you getting this error on atom startup even when it is not loading a js file, or only when you open a js file?

**Comment by amhed** [comment]
Mine got fixed after updating all plugins and restarting

**Comment by zp-j** [comment]
@ArtskydJ Only when I open a js file this error will pop up.

**Comment by TimMensch** [comment]
On 11/3/2015 8:34 PM, Joseph Dykstra wrote:
>
> I'm having trouble replicating this issue, and I'm on v1.8.3.
>
> Are you getting this error on atom startup even when it is not loading 
> a js file, or only when you open a js file?
>

I was getting it on Atom startup when the startup already had some 
number of JS files being restored.

When I disabled and then re-enabled the plug-in, the problem went away. 
So I'm guessing it didn't upgrade properly?

Tim

**Comment by ArtskydJ** [comment]
Will everyone experiencing the issue disable and re-enable `atom-jshint`? 

Please leave a comment whether it resolves the issue.

**Comment by MatthewHerbst** [comment]
Restarting Atom resolved the issue for me.

**Comment by KevinMartin** [comment]
`Disable -> Enable` didn't work for me.

I got it working again by doing `Disabled -> Restart Atom -> Enable`

**Comment by TimMensch** [comment]
I realize that's /actually/ what I did: I had disabled jshint because of 
the error, then restarted Atom at least once, and later enabled jshint 
and it worked.

**Comment by jpaulin** [comment]
I got plenty of this type of error (the top). Since it seems that at least some of those fresh ones popping up in Atom (in a red exception reporter box) are dups; 

I'll also Disable -> Restart -> Enable. And the result is: 
it's fixed!

I also had just updated 6 or 7 packages in Atom, before this issue came up. 
Atom 1.1.0 
JSHint 1.8.3

**Comment by dollschasingmen** [comment]
resolved this by upgrading to 1.8.3 and `Disable -> Restart -> Enable`

**Comment by paulbhartzog** [comment]
I am not even using atom-jshint (not listed in my packages) and I am still getting these error messages.  Suggestions?

**Comment by hchood** [comment]
resolved by upgrading to 1.8.3  - `apm install jshint` - and restarting.  Did not need to disable & reenable.

**Comment by sindresorhus** [comment]
Closing as this project is deprecated. 🌵
